version: "3.3"

services:
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    volumes:
      - ./:/var/www/neti
    ports:
      - 8099:80
    depends_on:
      - fpm
    links:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/neti
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 33062:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neti
